<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_Mfr_MValOp" Id="{9171697d-b160-4f3e-b83e-5f6ec447a5c6}" SpecialFunc="None">
    <Declaration><![CDATA[// Multistate value for operation.
FUNCTION_BLOCK FB_Mfr_MValOp EXTENDS FB_Mfr
VAR_OUTPUT PERSISTENT
	nVal : UDINT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[SUPER^();
]]></ST>
    </Implementation>
    <Property Name="Value" Id="{53b271d5-0dde-46a1-a33d-5ea4859bd211}">
      <Declaration><![CDATA[PROPERTY Value : UDINT]]></Declaration>
      <Get Name="Get" Id="{06a57c70-ce22-4896-b88c-5ae140dccd29}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[Value := nVal;]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{d79cf917-5510-409a-91ad-9391ab511270}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[nVal := Value;]]></ST>
        </Implementation>
      </Set>
    </Property>
  </POU>
</TcPlcObject>