<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_Mfr_BI" Id="{918b447c-736c-4cfb-bcc4-38e20023711c}" SpecialFunc="None">
    <Declaration><![CDATA[// Binary input.
FUNCTION_BLOCK FB_Mfr_BI EXTENDS FB_Mfr
VAR_OUTPUT
	bVal : BOOL;
END_VAR
VAR_INPUT CONSTANT
	bInvert : BOOL := FALSE;
END_VAR
VAR
	{region 'Raw data'}
		bRawData AT %I* : BOOL;
	{endregion}
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[SUPER^();

bVal := (bRawData = NOT bInvert);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>